force-app/main/default/objects/Coupon_Instance__c/Coupon_Instance__c.object-meta.xml
<CustomObject>
    <description>Coupon Instance Object</description>
    <label>Coupon Instance</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Coupon Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Instance__c/fields/Coupon_Item__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coupon Item Id</label>
    <referenceTo>Coupon_Item__c</referenceTo>
    <relationshipLabel>Coupon Instances</relationshipLabel>
    <relationshipName>Coupon_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/Coupon_Item__c.object-meta.xml
<CustomObject>
    <description>Coupon Item Object</description>
    <label>Coupon Item</label>
    <nameField>
        <displayFormat>CLS{0000}</displayFormat>
        <label>Coupon Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LWCCouponController.cls
public inherited sharing class LWCCouponController {
    @AuraEnabled
    public static list<Coupon_Instance__c> readCSVFile(Id idContentDocument){
        list<Coupon_Instance__c> lstCouponInstanceToInsert = new list<Coupon_Instance__c>();
        if(idContentDocument != null) {
            
            // getting File Data based on document id 
            ContentVersion objVersion = [SELECT Id, VersionData FROM ContentVersion 
            WHERE ContentDocumentId =:idContentDocument];
            // split the file data
            list<String> lstCSVLines = objVersion.VersionData.toString().split('\n');

            for(Integer i = 1; i < lstCSVLines.size(); i++){
                Coupon_Instance__c objCpInstance = new Coupon_Instance__c();
                list<String> csvRowData = lstCSVLines[i].split(',');
                System.debug('csvRowData====> '+csvRowData);
                objCpInstance.Coupon_Item__c = csvRowData[0]; 
                objCpInstance.HK_Id__c = csvRowData[1];
                lstCouponInstanceToInsert.add(objCpInstance);
            }

            try{    
                if(!lstCouponInstanceToInsert.isEmpty()) {
                    insert lstCouponInstanceToInsert;
                }
            }
            catch (Exception ex) {
                throw new AuraHandledException(ex.getMessage());
            } 
        }
        return lstCouponInstanceToInsert;    
    }
}