force-app/main/default/objects/Coupon_Instance__c/Coupon_Instance__c.object-meta.xml
<CustomObject>
    <description>Coupon Instance Object</description>
    <label>Coupon Instance</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Coupon Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Instance__c/fields/Coupon_Item__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coupon Item Id</label>
    <referenceTo>Coupon_Item__c</referenceTo>
    <relationshipLabel>Coupon Instances</relationshipLabel>
    <relationshipName>Coupon_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Coupon_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Item_Name__c</fullName>
    <formula>Coupon_Item__r.Coupon_Item_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coupon Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer ID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Instances</relationshipLabel>
    <relationshipName>Coupon_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;VALID&quot;</defaultValue>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <formula>Coupon_Item__r.Valid_From__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <formula>Coupon_Item__r.Valid_From__c  +  Coupon_Item__r.Valid_Length_in_days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/Coupon_Item__c.object-meta.xml
<CustomObject>
    <description>Coupon Item Object</description>
    <label>Coupon Item</label>
    <nameField>
        <displayFormat>CLS{0000}</displayFormat>
        <label>Coupon Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Item__c/fields/Coupon_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Item_Name__c</fullName>
    <label>Coupon Item Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <formula>Valid_Length_in_days__c  +  Valid_From__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CouponItemManager.cls
@RestResource(urlMapping='/cpinstance/*')
global with sharing class CouponItemManager {
    @HttpPost
    //@RestResource(urlMapping='/enquiry')
    global static Coupon_Instance__c enquiry(String cp_instance_id) {
        Coupon_Instance__c thiscpInstance = [
            SELECT Name,
            Coupon_Item__c,
            Coupon_Item_Name__c,
            Customer_ID__c,
            Expiry_Date__c,
            RecordTypeId,
            Status__c,
            Valid_From__c,
            Valid_To__c
            FROM Coupon_Instance__c
            WHERE (Name=:cp_instance_id)
        ];
        
        return thiscpInstance;
    }
    
    @HttpPatch
    //@RestResource(urlMapping='/transact')
    global static Coupon_Instance__c transact(String cp_instance_id) {
        Coupon_Instance__c thiscpInstance = [
            SELECT Name,
            Status__c
            FROM Coupon_Instance__c
            WHERE (Name=:cp_instance_id)
        ];
        
        thiscpInstance.Status__c = 'REDEEMED';
        
        update thiscpInstance; 
        
        return thiscpInstance;
    }
}