force-app/main/default/objects/Coupon_Instance__c/Coupon_Instance__c.object-meta.xml
<CustomObject>
    <description>Coupon Instance Object</description>
    <label>Coupon Instance</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Coupon Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Instance__c/fields/Coupon_Item__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coupon Item Id</label>
    <referenceTo>Coupon_Item__c</referenceTo>
    <relationshipLabel>Coupon Instances</relationshipLabel>
    <relationshipName>Coupon_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer ID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Instances</relationshipLabel>
    <relationshipName>Coupon_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coupon_Item__c/Coupon_Item__c.object-meta.xml
<CustomObject>
    <description>Coupon Item Object</description>
    <label>Coupon Item</label>
    <nameField>
        <displayFormat>CLS{0000}</displayFormat>
        <label>Coupon Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Item__c/fields/Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>Offer_Code__c</fullName>
    <label>Offer Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CreateCouponItemRest.cls
@RestResource(urlMapping='/createcpinstance/*')
global with sharing class CreateCouponItemRest {
    @HttpPost
    global static Coupon_Instance__c create(
        String offer_code,
        String customer_id
    ) {
        Coupon_Item__c cpitem = [
            Select Name, 
            Id
            From Coupon_Item__c
            Where (Offer_Code__c=:offer_code)
        ];
        
        Coupon_Instance__c newcpInstance = new Coupon_Instance__c(
            Coupon_Item__c = cpitem.Id,
            Customer_ID__c = customer_id
        );
        
        insert newcpInstance;
        
        Coupon_Instance__c result = [
            Select Name 
            from Coupon_Instance__c Where Id=:newcpInstance.Id
        ];
        
        return result;
    }
}