force-app/main/default/objects/Coupon_Instance__c/Coupon_Instance__c.object-meta.xml
<CustomObject>
    <description>Coupon Instance Object</description>
    <label>Coupon Instance</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Coupon Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;VALID&quot;</defaultValue>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon_Instance__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <formula>Coupon_Item__r.Valid_From__c  +  Coupon_Item__r.Valid_Length_in_days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchExpireCouponInstance.cls
global class BatchExpireCouponInstance implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query='SELECT Name, Valid_To__c from Coupon_Instance__c';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Coupon_Instance__c> cpInstanceLIst) {
        for(Coupon_Instance__c Coupon_Instance:cpInstanceLIst) {
            if(Coupon_Instance.Valid_To__c < Date.today()) {
                Coupon_Instance.Status__c = 'EXPIRED';
            }
        }
        try{
            update cpInstanceLIst;
        } catch(Exception e) {
            System.debug(e);
        }
        
    }
    global void finish(Database.BatchableContext BC) {

    }
}